version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: market-app
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: market
      POSTGRES_SSL_MODE: disable
      POSTGRES_MIGRATE: "true"
      HTTP_PORT: 8080
      LOG_LEVEL: info
    ports:
      - "8080:8080"
    networks:
      - market-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: market
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - market-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  market-network:
    driver: bridge